import { UserProfileDto, AuthResponse } from '../types/auth.types';
import { OutbreakResponse, OutbreakStatisticsResponse } from '../types/outbreak.types';
import { DiseaseAnalyticsResponse } from '../types/analytics.types';
import { DiseaseMetadata, DiseaseReportResponse } from '../types/disease.types';
import { GeoJsonFeatureCollection, HeatmapPoint } from '../types/gis.types';
import { VaccinationAnalyticsResponse } from '../types/vaccination.types';
import { OperationalAlertResponse } from '../types/alerts.types';
import { SystemConfigurationResponse } from '../types/system.types';

export const mockAdminUser: UserProfileDto = {
  id: 'usr-admin-001',
  fullName: 'Dr. Rajesh Sharma (Director)',
  email: 'admin@vetra.gov.in',
  phone: '+919876543210',
  role: 'ADMINISTRATOR',
  active: true,
  preferredLanguage: 'en',
  district: 'Pune',
  taluka: 'Baramati',
  village: 'Baramati HQ',
  state: 'Maharashtra',
};

export const mockOfficerUser: UserProfileDto = {
  id: 'usr-off-002',
  fullName: 'Vikram Deshmukh (Surveillance Officer)',
  email: 'officer@vetra.gov.in',
  phone: '+919876543211',
  role: 'GOVERNMENT_OFFICER',
  active: true,
  preferredLanguage: 'en',
  district: 'Pune',
  taluka: 'Baramati',
  village: 'Baramati Central',
  state: 'Maharashtra',
};

export const mockAuthResponse = (identifier: string): AuthResponse => {
  const isAdmin = identifier.toLowerCase().includes('admin');
  return {
    accessToken: 'demo_mock_jwt_token_pashu_sathi_gov_2026',
    refreshToken: 'demo_mock_jwt_refresh_token_pashu_sathi_gov_2026',
    tokenType: 'Bearer',
    expiresIn: 86400,
    user: isAdmin ? mockAdminUser : mockOfficerUser,
  };
};

export const mockOutbreakStatistics: OutbreakStatisticsResponse = {
  totalOutbreaks: 14,
  activeOutbreaks: 5,
  resolvedOutbreaks: 9,
  highRiskOutbreaks: 3,
};

export const mockOutbreaks: OutbreakResponse[] = [
  {
    id: 'ob-fmd-pune-01',
    diseaseName: 'Foot-and-Mouth Disease (FMD)',
    severity: 'HIGH',
    status: 'ACTIVE',
    riskScore: 'CRITICAL',
    compositeRiskScore: 88,
    centerLatitude: 18.1512,
    centerLongitude: 74.5778,
    radiusKm: 5.0,
    affectedReportsCount: 8,
    evaluationWindowHours: 48,
    lastCaseReportedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 28).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    riskBreakdown: {
      clusterScore: 92,
      weatherScore: 78,
      historyScore: 85,
      vaccinationGapScore: 95,
      weatherTemperature: 28.5,
      weatherHumidity: 84,
      weatherPrecipitation: 12.4,
      vaccinationCoveragePct: 62.5,
      riskExplanation: 'High cluster density combined with 84% monsoon humidity and low ring vaccination buffer.',
      recommendedAction: 'Immediate ring-vaccination dispatch and livestock movement embargo within 25km buffer.',
    },
  },
  {
    id: 'ob-lsd-satara-02',
    diseaseName: 'Lumpy Skin Disease (LSD)',
    severity: 'HIGH',
    status: 'ACTIVE',
    riskScore: 'HIGH',
    compositeRiskScore: 76,
    centerLatitude: 17.6805,
    centerLongitude: 74.0183,
    radiusKm: 7.5,
    affectedReportsCount: 6,
    evaluationWindowHours: 48,
    lastCaseReportedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    riskBreakdown: {
      clusterScore: 72,
      weatherScore: 81,
      historyScore: 68,
      vaccinationGapScore: 84,
      weatherTemperature: 26.0,
      weatherHumidity: 79,
      weatherPrecipitation: 4.2,
      vaccinationCoveragePct: 71.0,
      riskExplanation: 'Elevated vector breeding conditions with cutaneous nodular lesions across multiple cattle herds.',
      recommendedAction: 'Deploy vector control and homologous Goat Pox vaccine ring within 15km perimeter.',
    },
  },
  {
    id: 'ob-anthrax-solapur-03',
    diseaseName: 'Anthrax Suspicion',
    severity: 'HIGH',
    status: 'ACTIVE',
    riskScore: 'CRITICAL',
    compositeRiskScore: 94,
    centerLatitude: 17.6599,
    centerLongitude: 75.9064,
    radiusKm: 10.0,
    affectedReportsCount: 3,
    evaluationWindowHours: 48,
    lastCaseReportedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    riskBreakdown: {
      clusterScore: 96,
      weatherScore: 70,
      historyScore: 90,
      vaccinationGapScore: 98,
      weatherTemperature: 31.2,
      weatherHumidity: 58,
      weatherPrecipitation: 0.0,
      vaccinationCoveragePct: 45.0,
      riskExplanation: 'Peracute sudden death with non-clotting dark discharge. Severe zoonotic biohazard.',
      recommendedAction: 'Enforce quarantine. Prohibit opening carcasses. Administer ring spore vaccine.',
    },
  },
  {
    id: 'ob-ppr-ahmednagar-04',
    diseaseName: 'Peste des Petits Ruminants (PPR)',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    riskScore: 'MEDIUM',
    compositeRiskScore: 48,
    centerLatitude: 19.0952,
    centerLongitude: 74.7496,
    radiusKm: 4.0,
    affectedReportsCount: 4,
    evaluationWindowHours: 48,
    lastCaseReportedAt: new Date(Date.now() - 3600000 * 9).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 42).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 9).toISOString(),
    riskBreakdown: null,
  },
  {
    id: 'ob-brucellosis-nashik-05',
    diseaseName: 'Bovine Brucellosis',
    severity: 'LOW',
    status: 'ACTIVE',
    riskScore: 'LOW',
    compositeRiskScore: 24,
    centerLatitude: 19.9975,
    centerLongitude: 73.7898,
    radiusKm: 3.5,
    affectedReportsCount: 2,
    evaluationWindowHours: 48,
    lastCaseReportedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    riskBreakdown: null,
  },
];

export const mockDiseaseAnalytics: DiseaseAnalyticsResponse = {
  totalOutbreaks: 14,
  activeOutbreaks: 5,
  resolvedOutbreaks: 9,
  highRiskOutbreaks: 3,
  averageResolutionTimeHours: 32.5,
  diseaseDistribution: {
    'Foot-and-Mouth Disease (FMD)': 5,
    'Lumpy Skin Disease (LSD)': 4,
    'Anthrax Suspicion': 1,
    'Peste des Petits Ruminants (PPR)': 2,
    'Bovine Brucellosis': 2,
  },
  mostCommonDiseases: [
    'Foot-and-Mouth Disease (FMD)',
    'Lumpy Skin Disease (LSD)',
    'Peste des Petits Ruminants (PPR)',
    'Bovine Brucellosis',
    'Anthrax Suspicion',
  ],
  reportsByConfidenceSource: {
    VETERINARIAN: 18,
    AI_VERIFIED: 12,
    LAB_CONFIRMED: 6,
    GOVERNMENT: 4,
  },
};

export const mockReports: DiseaseReportResponse[] = [
  {
    id: 'rep-001',
    animalId: 'an-992',
    tagNumber: 'MH-12-P-8821',
    animalName: 'Gauri (Gir Cow)',
    medicalRecordId: 'med-101',
    aiScanId: 'scan-201',
    reportedById: 'usr-fm-01',
    reportedByName: 'Ramesh Patil (Baramati)',
    reportSource: 'FARMER_REPORT',
    diagnosisConfidenceSource: 'VETERINARIAN',
    diseaseName: 'Foot-and-Mouth Disease (FMD)',
    diagnosisStatus: 'CONFIRMED',
    latitude: 18.152,
    longitude: 74.576,
    notes: 'Severe vesicular lesions on tongue & hooves. High fever. Dr. Anita Joshi confirmed.',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'rep-002',
    animalId: 'an-993',
    tagNumber: 'MH-12-P-8834',
    animalName: 'Kaveri (Sahiwal)',
    medicalRecordId: 'med-102',
    aiScanId: 'scan-202',
    reportedById: 'usr-fm-02',
    reportedByName: 'Suresh More (Baramati)',
    reportSource: 'FARMER_REPORT',
    diagnosisConfidenceSource: 'VETERINARIAN',
    diseaseName: 'Foot-and-Mouth Disease (FMD)',
    diagnosisStatus: 'CONFIRMED',
    latitude: 18.149,
    longitude: 74.581,
    notes: 'Mouth erosions, severe drop in milk yield. Verified on-site by Mobile Vet Unit.',
    createdAt: new Date(Date.now() - 3600000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'rep-003',
    animalId: 'an-994',
    tagNumber: 'MH-11-S-4412',
    animalName: 'Raja (Khillari Bull)',
    medicalRecordId: 'med-103',
    aiScanId: 'scan-203',
    reportedById: 'usr-fm-03',
    reportedByName: 'Dnyaneshwar Jadhav (Satara)',
    reportSource: 'FARMER_REPORT',
    diagnosisConfidenceSource: 'VETERINARIAN',
    diseaseName: 'Lumpy Skin Disease (LSD)',
    diagnosisStatus: 'CONFIRMED',
    latitude: 17.682,
    longitude: 74.021,
    notes: 'Generalized cutaneous nodules (2-5cm), enlarged lymph nodes. Verified by Dr. Chavan.',
    createdAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'rep-004',
    animalId: 'an-995',
    tagNumber: 'MH-13-A-1109',
    animalName: 'Krishna (Murrah Buffalo)',
    medicalRecordId: 'med-104',
    aiScanId: 'scan-204',
    reportedById: 'usr-fm-04',
    reportedByName: 'Balasaheb Shinde (Solapur)',
    reportSource: 'FARMER_REPORT',
    diagnosisConfidenceSource: 'AI_VERIFIED',
    diseaseName: 'Anthrax Suspicion',
    diagnosisStatus: 'SUSPECTED',
    latitude: 17.661,
    longitude: 75.908,
    notes: 'Sudden collapse, blood exudation from nostrils. Biohazard containment initiated.',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'rep-005',
    animalId: 'an-996',
    tagNumber: 'MH-17-G-7701',
    animalName: 'Sonu (Osmanabadi Goat)',
    medicalRecordId: 'med-105',
    aiScanId: 'scan-205',
    reportedById: 'usr-fm-05',
    reportedByName: 'Kisanrao Kadam (Rahuri)',
    reportSource: 'VET_CONSULTATION',
    diagnosisConfidenceSource: 'VETERINARIAN',
    diseaseName: 'Peste des Petits Ruminants (PPR)',
    diagnosisStatus: 'CONFIRMED',
    latitude: 19.098,
    longitude: 74.752,
    notes: 'Erosive stomatitis, mucopurulent ocular-nasal discharge. Isolated herd.',
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const mockOutbreaksGeoJson: GeoJsonFeatureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [74.5778, 18.1512],
      },
      properties: {
        id: 'ob-fmd-pune-01',
        diseaseName: 'Foot-and-Mouth Disease (FMD)',
        severity: 'HIGH',
        status: 'ACTIVE',
        riskScore: 'CRITICAL',
        trend: 'ESCALATING',
        radiusKm: 5.0,
        affectedReportsCount: 8,
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [74.0183, 17.6805],
      },
      properties: {
        id: 'ob-lsd-satara-02',
        diseaseName: 'Lumpy Skin Disease (LSD)',
        severity: 'HIGH',
        status: 'ACTIVE',
        riskScore: 'HIGH',
        trend: 'STABLE',
        radiusKm: 7.5,
        affectedReportsCount: 6,
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [75.9064, 17.6599],
      },
      properties: {
        id: 'ob-anthrax-solapur-03',
        diseaseName: 'Anthrax Suspicion',
        severity: 'HIGH',
        status: 'ACTIVE',
        riskScore: 'CRITICAL',
        trend: 'ESCALATING',
        radiusKm: 10.0,
        affectedReportsCount: 3,
      },
    },
  ],
};

export const mockHeatmapData: HeatmapPoint[] = [
  { latitude: 18.1512, longitude: 74.5778, intensityWeight: 0.95, caseCount: 8, diseaseName: 'FMD' },
  { latitude: 18.149, longitude: 74.581, intensityWeight: 0.88, caseCount: 5, diseaseName: 'FMD' },
  { latitude: 17.6805, longitude: 74.0183, intensityWeight: 0.85, caseCount: 6, diseaseName: 'LSD' },
  { latitude: 17.6599, longitude: 75.9064, intensityWeight: 0.98, caseCount: 3, diseaseName: 'Anthrax' },
  { latitude: 19.0952, longitude: 74.7496, intensityWeight: 0.65, caseCount: 4, diseaseName: 'PPR' },
  { latitude: 19.9975, longitude: 73.7898, intensityWeight: 0.45, caseCount: 2, diseaseName: 'Brucellosis' },
];

export const mockDistricts: string[] = [
  'Pune',
  'Satara',
  'Ahmednagar',
  'Solapur',
  'Nashik',
  'Kolhapur',
  'Sangli',
  'Aurangabad',
];

export const mockDiseaseRegistry: DiseaseMetadata[] = [
  {
    id: 'dis-001',
    diseaseName: 'Foot-and-Mouth Disease (FMD)',
    severity: 'HIGH',
    zoonotic: false,
    reportable: true,
    mortality: 'LOW_ADULT_HIGH_CALF',
    defaultRadiusKm: 25,
    minimumCases: 3,
    speciesAffected: 'Cattle, Buffalo, Sheep, Goat, Pig',
  },
  {
    id: 'dis-002',
    diseaseName: 'Lumpy Skin Disease (LSD)',
    severity: 'HIGH',
    zoonotic: false,
    reportable: true,
    mortality: 'MODERATE',
    defaultRadiusKm: 25,
    minimumCases: 3,
    speciesAffected: 'Cattle, Buffalo',
  },
  {
    id: 'dis-003',
    diseaseName: 'Anthrax Suspicion',
    severity: 'CRITICAL',
    zoonotic: true,
    reportable: true,
    mortality: 'EXTREMELY_HIGH',
    defaultRadiusKm: 25,
    minimumCases: 1,
    speciesAffected: 'Cattle, Buffalo, Sheep, Goat, Human',
  },
  {
    id: 'dis-004',
    diseaseName: 'Peste des Petits Ruminants (PPR)',
    severity: 'MEDIUM',
    zoonotic: false,
    reportable: true,
    mortality: 'HIGH_SMALL_RUMINANTS',
    defaultRadiusKm: 15,
    minimumCases: 3,
    speciesAffected: 'Sheep, Goat',
  },
  {
    id: 'dis-005',
    diseaseName: 'Bovine Brucellosis',
    severity: 'LOW',
    zoonotic: true,
    reportable: true,
    mortality: 'LOW_CHRONIC',
    defaultRadiusKm: 10,
    minimumCases: 2,
    speciesAffected: 'Cattle, Buffalo, Human',
  },
];

export const mockVaccinationAnalytics: VaccinationAnalyticsResponse = {
  totalRegisteredLivestock: 148500,
  totalVaccinatedLivestock: 118200,
  totalUnvaccinatedLivestock: 30300,
  overallCoveragePercentage: 79.6,
  overallImmunityGapPercentage: 20.4,
  pathogenCoverage: [
    {
      diseaseName: 'Foot-and-Mouth Disease (FMD)',
      vaccinatedCount: 64200,
      eligibleCount: 75000,
      coveragePercentage: 85.6,
      immunityGapPercentage: 14.4,
      targetCoveragePercentage: 90.0,
      status: 'ADEQUATE',
    },
    {
      diseaseName: 'Lumpy Skin Disease (LSD)',
      vaccinatedCount: 32000,
      eligibleCount: 42000,
      coveragePercentage: 76.2,
      immunityGapPercentage: 23.8,
      targetCoveragePercentage: 85.0,
      status: 'DEFICIT',
    },
    {
      diseaseName: 'Brucellosis (Calfhood S19)',
      vaccinatedCount: 12000,
      eligibleCount: 18500,
      coveragePercentage: 64.9,
      immunityGapPercentage: 35.1,
      targetCoveragePercentage: 80.0,
      status: 'CRITICAL_GAP',
    },
  ],
  zoneVaccinationGaps: [
    {
      outbreakId: 'ob-fmd-pune-01',
      zoneName: 'Baramati Taluka Containment Buffer',
      diseaseName: 'Foot-and-Mouth Disease (FMD)',
      latitude: 18.1512,
      longitude: 74.5778,
      radiusKm: 25.0,
      totalAnimals: 42000,
      vaccinatedAnimals: 31500,
      coveragePercentage: 75.0,
      immunityGapPercentage: 25.0,
      riskLevel: 'HIGH',
    },
    {
      outbreakId: 'ob-anthrax-solapur-03',
      zoneName: 'Madha Containment Zone',
      diseaseName: 'Anthrax Suspicion',
      latitude: 17.6599,
      longitude: 75.9064,
      radiusKm: 25.0,
      totalAnimals: 18000,
      vaccinatedAnimals: 8100,
      coveragePercentage: 45.0,
      immunityGapPercentage: 55.0,
      riskLevel: 'CRITICAL',
    },
  ],
  priorityDeficitZones: [
    {
      outbreakId: 'ob-anthrax-solapur-03',
      zoneName: 'Madha Canal Belt (Solapur)',
      primaryDisease: 'Anthrax Suspicion',
      immunityGapPercentage: 55.0,
      outbreakRiskScore: 94,
      operationalPriority: 'URGENT_RING_VACCINATION',
      recommendedAction: 'Dispatch 10,000 spore vaccine doses to Taluka Veterinary Dispensary Madha.',
    },
    {
      outbreakId: 'ob-fmd-pune-01',
      zoneName: 'Baramati High-Density Dairy Belt',
      primaryDisease: 'Foot-and-Mouth Disease (FMD)',
      immunityGapPercentage: 25.0,
      outbreakRiskScore: 88,
      operationalPriority: 'URGENT_RING_VACCINATION',
      recommendedAction: 'Deploy 5 Mobile Veterinary Units (MVUs) with cold-chain liquid nitrogen containers.',
    },
  ],
};

export const mockOperationalAlerts: OperationalAlertResponse[] = [
  {
    id: 'alt-001',
    eventType: 'CRITICAL_OUTBREAK_DETECTED',
    title: 'Emergency 25km Ring Vaccination Directive: Baramati Cluster',
    diseaseName: 'Foot-and-Mouth Disease (FMD)',
    locationName: 'Baramati, Pune District (Maharashtra)',
    latitude: 18.1512,
    longitude: 74.5778,
    severity: 'CRITICAL',
    compositeRiskScore: 88,
    vaccinationGapScore: 95,
    affectedCasesCount: 8,
    detectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    source: 'POSTGIS_CLUSTER_ENGINE',
    status: 'ACTIVE',
    whyItMatters: 'PostGIS spatial cluster triggered with 8 verified cases. 25km buffer containment zone established.',
    recommendedNextStep: 'Mobilize 5 Mobile Veterinary Units (MVUs) with cold-chain liquid nitrogen containers immediately.',
    relatedOutbreakId: 'ob-fmd-pune-01',
    relatedReportId: 'rep-001',
  },
  {
    id: 'alt-002',
    eventType: 'IMMUNITY_GAP_OVERLAP',
    title: 'Anthrax Biohazard Quarantine Protocol: Madha Cluster',
    diseaseName: 'Anthrax Suspicion',
    locationName: 'Madha, Solapur District (Maharashtra)',
    latitude: 17.6599,
    longitude: 75.9064,
    severity: 'CRITICAL',
    compositeRiskScore: 94,
    vaccinationGapScore: 98,
    affectedCasesCount: 3,
    detectedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    source: 'MULTI_SIGNAL_RISK_ENGINE',
    status: 'ACTIVE',
    whyItMatters: 'Suspected Anthrax with sudden mortality and non-clotting dark blood. Carcass opening strictly prohibited.',
    recommendedNextStep: 'Enforce 6-foot deep burial with quicklime buffer. Notify District Medical Officer for farmer screening.',
    relatedOutbreakId: 'ob-anthrax-solapur-03',
    relatedReportId: 'rep-004',
  },
];

export const mockSystemConfiguration: SystemConfigurationResponse = {
  surveillance: {
    weightCluster: 0.4,
    weightWeather: 0.2,
    weightHistory: 0.2,
    weightVaccination: 0.2,
    lowThreshold: 30,
    mediumThreshold: 55,
    highThreshold: 80,
    confirmedCaseMultiplier: 1.0,
    suspectedCaseMultiplier: 0.5,
  },
  weather: {
    provider: 'Open-Meteo & IMD Agro-Advisory API',
    enabled: true,
    cacheTtlMinutes: 60,
    timeoutSeconds: 5,
    connectTimeoutSeconds: 3,
    apiEndpoint: 'https://api.open-meteo.com/v1/forecast',
  },
  alerts: {
    epidemiologicalRiskThreshold: 75,
    operationalPriorityFormula: 'CompositeScore * 0.5 + ImmunityGap * 0.3 + CaseVelocity * 0.2',
    evaluationMode: 'REAL_TIME_CRON_60S',
  },
  system: {
    serviceName: 'PASHU SATHI Surveillance Intelligence Core',
    environment: 'PRODUCTION-AZURE',
    version: '2.4.0-SIH2026',
    databaseEngine: 'PostgreSQL 16 + PostGIS 3.4 Spatial Clustering',
    connectionPool: 'HikariCP Max-20 Active',
    securityStandard: 'Stateless 256-bit RS256 JWT RBAC',
    auditTelemetry: 'DAHD Compliance Log Audit Enabled',
  },
};
